info.app:
  name: "@project.parent.name@"
  description: "@project.parent.description@"
  version: "@project.parent.version@"
  final-name: "@project.build.finalName@"

server:
  port: ${PORT:8080}
  context-path: "/@context.path@/@context.version@"

datasource:
  name: in_memory
  initialize: true
  url: jdbc:h2:mem:dev_db
  username: guest
  password: changeIt
  driverClassName: org.h2.Driver